# Site settings
title: Amir Mohammad Safari Livari
description: A blog about Amir Mohammad Safari Livari
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: JARVIS-AI
user_description: Amir Mohammad Safari Livari from Tehran born 19th january of 1997,
     Started learning how to program when he was 8 and wrote his "Hello World" before starting guidance highschool!
     Then He did not do something special other than studying his lessons till 2009,
     by that year, he started going deeper in algorithms and datastructure and Mathematics Discrete.
     After he learned enough, he started to develop and run his own apps both desktop and small platforms and websites.
     Now he is writing his experiences with gnu/linux and macOS in his website or blog, amshq.
     Beside that He is studying university and travle to London soon.
user_title: Software Developer
email: ams.h4ck3r@gmail.com
twitter_username: JARVISAI
github_username:  JARVIS-AI

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'node_modules']
